# -------------------------------------------------------------------------
#             BPAEngine - Better Plymouth Animations Engine
# -------------------------------------------------------------------------
# This is an engine based on plymouth that enable people to develop better
# boot screens without much effort.
#
#
# Author: Moisés Déniz Alemán
# GitHub: https://github.com/mdeniz/BPAEngine
# License: GPL v3
#

BPAE = [];
