#------------------------------- Variators --------------------------------------

Variator = fun (config)
  {
    new_variator = [] | global.Variator;
    new_variator.type = config.type | "linear";
    new_variator.constant = config.constant | 1.0;
    return new_variator;
  } | [];

Variator.Next = fun (value, delta)
  {
    if (type == "linear")
      return value + constant;
    if (type == "random")
      return value + (Math.Random() * constant) - constant / 2;
  };
