
# -------------------------------------------------------------------------
# Setup BPAE.World
# -------------------------------------------------------------------------

DEBUG = TRUE;

WORLD = BPAE.World();

WORLD.Setup = fun (mode)
  {
    Add(BPAE.Background());

    if (mode == "shutdown") # For having 2 kinds of dialogs in the same preview
    {
      local.config.mode = "window";
    }
    Add(BPAE.Dialog(local.config));
  };

WORLD.Build();
