
# -------------------------------------------------------------------------
# Setup World
# -------------------------------------------------------------------------

DEBUG=1;

WORLD = World();

WORLD.Setup = fun ()
  {
    Add(Background());
    
    if (Plymouth.GetMode () == "shutdown") # For having 2 kinds of dialogs in the same preview
    {
      local.config.mode = "window";
    }
    Add(Dialog(local.config));
  };

WORLD.Build();
