
# -------------------------------------------------------------------------
# Static Image
# -------------------------------------------------------------------------

StaticImage = fun (config)
  {
    new_object =  [] | global.StaticImage | global.Object(config);
    new_object.class = "StaticImage";
    return new_object;
  } | [];

StaticImage.Update = fun (delta)
  {
    # Avoid updating coordinates, animations and so on
  };
