
# -------------------------------------------------------------------------
# Static Image
# -------------------------------------------------------------------------

BPAE.StaticImage = fun (config)
  {
    new_object =  [] | global.BPAE.StaticImage | global.BPAE.Object(config);
    new_object.class = "BPAE.StaticImage";
    return new_object;
  } | [];

BPAE.StaticImage.Update = fun (delta)
  {
    # Avoid updating coordinates, animations and so on
  };
