
# -------------------------------------------------------------------------
# Array helper functions
# -------------------------------------------------------------------------

Array.Size = fun(array)
  {
    local.size = 0;
    while (array[local.size])
      local.size++;
    return local.size;
  };

Array.Add = fun(array, element)
  {
    array[Array.Size(array)] = element;
    return array;
  };
