
# -------------------------------------------------------------------------
# Setup World
# -------------------------------------------------------------------------

DEBUG = TRUE;

WORLD = World();

WORLD.Setup = fun ()
  {
    Add(Background());

    if (Plymouth.GetMode() == "shutdown") # For having 2 kinds of dialogs in the same preview
    {
      local.config.mode = "window";
    }
    Add(PasswordDialog(local.config));
  };

WORLD.Build();
