
# -------------------------------------------------------------------------
# Setup BPAE.World
# -------------------------------------------------------------------------

DEBUG = TRUE;

WORLD = BPAE.World();

WORLD.Setup = fun ()
  {
    Add(BPAE.Background());

    if (Plymouth.GetMode() == "shutdown") # For having 2 kinds of dialogs in the same preview
    {
      local.config.mode = "window";
    }
    Add(BPAE.PasswordDialog(local.config));
  };

WORLD.Build();
